### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Croblant** [ClementSicard/Musescore-Stats#1]
Hello,

I'm very interested of your musescore files of Sofiane Pamart to play them on musescore drived organ.
The scores have been removed from musescore.com.
Do you think it's possible to share them ?

Regards.

**Comment by clementsicard** [comment]
Hi, no I won't repost them as they have been removed for copyright reasons. However, a book is now available so if you want the sheets you should buy them.
PS: note that this is Github, a tool that I use for work, and creating an issue on this old repo that has nothing to do with the sheets on my private account feels a bit weird

**Comment by Croblant** [comment]
Sorry it is the only way i found to contact you.
I wanted to send you a message on linkedin but i can't because we are not linked.

In fact i need musescore files to send MIDI message to drive our organ and not pdf.
https://www.youtube.com/watch?v=Nhll_KHVvMs&list=PL_jiNOi-bRTC71IkMD6ZEW_Q0PLUcsFNf
And i see that you did that very well.
And the book for planet is sold out.
I hoped that you could send a zip in private.

But i understand your position and will wait the new edition and will rewrite on musescore the music.
Regards.
Have a nice week-end.
